### ISSUE TITLE
Домашнее задание 1

### ISSUE THREAD

**Issue by dnkorbut** [dnkorbut/3d-test#1]
Форкнуть проект и реализовать вращение головы ;)

**Comment by kirillshevch** [comment]
@dnkorbut зачем форкать?

**Comment by dnkorbut** [comment]
ну не знаю как подругому дописать чтто-то в проект

**Comment by kirillshevch** [comment]
@dnkorbut 
git checkout -b имя-новой ветки
git commit -am "описание изменений"
git push origin имя-новой-ветки

дальше в интерфейсе гитхаба открывай pull request, смотри изменения и мержи в мастер

**Comment by dnkorbut** [comment]
это ли не тоже самое?

**Comment by kirillshevch** [comment]
@dnkorbut нет :)

**Comment by dnkorbut** [comment]
тогда сделай задание ;)

**Comment by kirillshevch** [comment]
@dnkorbut, если появятся идеи - присоединяюсь
